module.exports = {
  apps: [
    {
      name: 'agency-web',
      script: 'npm',
      args: 'start',
      cwd: '/home/agency/SoftSite',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/home/agency/logs/web-app/err.log',
      out_file: '/home/agency/logs/web-app/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
    },
    {
      name: 'agency-bot',
      script: 'dist/index.js',
      cwd: '/home/agency/TgBot',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      error_file: '/home/agency/logs/bot/err.log',
      out_file: '/home/agency/logs/bot/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 10000,
    },
  ],
}

